// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccessToken  string
	RefreshToken string
	ExpiresAt    int64
	CreatedAt    pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
}
